---
- name: Install ufw package.
  apt:
    name: ufw
    state: present

- name: Specify allowed ports in firewall config.
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443

- name: Open UDP ports 10000 to 20000 for jitsi-videobridge
  ufw:
    rule: allow
    port: '10000:20000'
    proto: udp

- name: Ensure UFW is running.
  ufw:
    name: ufw
    state: enabled
